version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: real_estate_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supertajnehaslo123
      POSTGRES_DB: real_estate_data
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql